### ISSUE TITLE
Software feira

### ISSUE THREAD

**Issue by durvalpaiva** [ricardocassiano04/feirafacil#1]
# Dicionário para armazenar os produtos e seus respectivos estoques
estoque = {
    'alface': 50,
    'tomate': 100,
    'cebola': 75
}

# Variável para controlar o valor total das vendas
total_vendas = 0.0

# Função para realizar uma venda
def realizar_venda(produto, quantidade, valor_pago):
    global total_vendas

    # Verifica se o produto está disponível no estoque
    if produto in estoque and estoque[produto] >= quantidade:
        # Calcula o valor total da venda
        valor_total = quantidade * valor_unitario[produto]

        # Verifica se o valor pago é suficiente
        if valor_pago >= valor_total:
            # Atualiza o estoque
            estoque[produto] -= quantidade

            # Atualiza o valor total das vendas
            total_vendas += valor_total

            # Calcula o troco
            troco = valor_pago - valor_total

            # Imprime o recibo da venda
            print('-------------------------')
            print('Recibo de Venda')
            print('-------------------------')
            print('Produto: ', produto)
            print('Quantidade: ', quantidade)
            print('Valor Total: R$', valor_total)
            print('Valor Pago: R$', valor_pago)
            print('Troco: R$', troco)
            print('-------------------------')
        else:
            print('Valor pago insuficiente!')
    else:
        print('Produto indisponível no estoque ou quantidade insuficiente!')

# Função para exibir o estoque atual
def exibir_estoque():
    print('-------------------------')
    print('Estoque Atual')
    print('-------------------------')
    for produto, quantidade in estoque.items():
        print(produto.capitalize(), ':', quantidade)
    print('-------------------------')

# Função para exibir o valor total das vendas
def exibir_total_vendas():
    print('-------------------------')
    print('Total de Vendas: R$', total_vendas)
    print('-------------------------')

# Valor unitário de cada produto
valor_unitario = {
    'alface': 2.5,
    'tomate': 3.0,
    'cebola': 1.0
}

# Exemplo de uso do programa
realizar_venda('alface', 2, 10.0)
realizar_venda('tomate', 5, 20.0)

exibir_estoque()
exibir_total_vendas()

**Comment by ricardocassiano04** [comment]
Olá @durvalpaiva 

Você me deu uma ótima ideia. 

Ainda não cheguei nessa parte do projeto. Tô criando o banco de dados ainda (no tempo que sobra).

Acredito que você queria abrir, ao invés de uma issue, um pull request.

Obrigado pela contribuição.
